### PR TITLE
[feat] Extract parsing of students file into a hook function

### PR DESCRIPTION
**Pull request by slarse**
#880 

This PR is part refactor, part feature. It extracts the parsing of the students file into a hook function such that the exact implementation can be overridden with plugins. This opens up for implementing students file parsing in any way one wishes to.

@davbeek I've briefly played around with this to implement a plugin for to parse YAML files, allowing one to specify something like this:

```yml
some-team:
    members: [alice, eve, bob]
other-team:
    members: [simon, ric]
```

This would create the teams `some-team` and `other-team` with the specified members, and any associated repos would by default then have names prefixed with those team names (as usual). You could of course add that group id of yours as part of the team name. I haven't decided on the details here, but the good news is that supporting your use case is not hard at all.

@htdebeer-tue I recall that at some point we discussed fetching student lists from Canvas. I believe that with this hook, that should be possible.

### CODE REVIEW

**Comment by slarse** [comment]
@tohanss Ping for review

**Comment by davbeek** [comment]
Sound like a good solution! Either my TA or @htdebeer-tue will be able to continue with the plugin.

**Comment by slarse** [comment]
@davbeek I might be including it directly in RepoBee, because it's really not difficult. At the very least I can provide the code for the prototype. The thing that slightly holds me back is that I don't really want to include a whole YAML library as a dependency for this one thing. But it would be very neat to be able to deal with YAML-like files, so there may be a case for writing a parser for a very tiny subset of YAML.

**Review by tohanss — APPROVED** [review]
Not many changes to look at, the old code looks great and the added feature seems really useful. i like it!

**Comment by slarse** [comment]
Thanks @tohanss!

**Comment by htdebeer-tue** [comment]
Nice feature! 

Yes, @slarse, we did talk about fetching student lists from Canvas. That would be a nice feature for my repobee-canvas plugin because it would simplify using repobee.


However, during last year's fourth term, a colleague tried repobee-canvas and discovered that a small number of students were not given the same gitlab ID as stored in Canvas. As a result, I might not be able to rely on Canvas' data and have to work with a separate file anyway. On the other hand, I could keep track of only the students with an "incorrect" ID in the separate file.

**Comment by slarse** [comment]
> However, during last year's fourth term, a colleague tried repobee-canvas and discovered that a small number of students were not given the same gitlab ID as stored in Canvas.

Ah, that's a bummer. Well, the functionality is there now anyway!

**Pull request merged**
