### PR TITLE
fix: Fix crash when using subgroup as target org

### PR DESCRIPTION
**Pull request by sakehl**
Needed the full path, see issue https://github.com/repobee/repobee/issues/890

### CODE REVIEW

**Comment by slarse** [comment]
@sakehl Do you mind if I push some updates to this branch? I would like to a) run the GitLab system tests, and b) add at least one new test where a subgroup is used as the target group. I'm not super confident that works as expected as I never had that in mind in designing the whole thing, and your solution seems almost too easy :)

**Comment by sakehl** [comment]
@slarse Sure go ahead, I've given you access to the forked-repository.

And no problem, I'm just mostly happy that everything works again from my end.

**Comment by slarse** [comment]
> @slarse Sure go ahead, I've given you access to the forked-repository.
> 
> And no problem, I'm just mostly happy that everything works again from my end.

I actually don't need access to your fork, it's sufficient that you tick the little box in the bottom right here on the PR saying `Allow edits and access to secrets by maintainers` :)

**Comment by slarse** [comment]
macOS tests are failing, but that's just a random backend problem with GHA, see actions/virtual-environments#841

Other than that, all regression tests for GitLab are green, and the new setup test works. @sakehl This feature is by no means exhaustively tested, but it appears to just work! Please do be on the lookout for problems and we'll patch them as we go along :)

**Comment by sakehl** [comment]
Perfect thanks, I'll let you know if I run into anything else.

**Pull request merged**
