### PR TITLE
[misc] Add Dockerfile for public image

### LINKED ISSUE #735: Docker image on Docker Hub
There is an image for testing (`Dockerfile.test`). Can you make an official streamlined image and put it on [Docker Hub](https://hub.docker.com)?

### PR DESCRIPTION
**Pull request by slarse**
#735 

This is a draft for the Dockerfile for the public image of RepoBee. To use a config, one can mount a directory containing the config like so:

```bash
$ docker run --rm \
    -v /path/to/dir/with/config:/home/repobee/.config/repobee/ \
    -t repobee:latest \
    repobee config show
```

My currently best idea for making the install directory persistent (to allow for using plugins) is something like this.

```bash
# first copy the contents of the container's install directory into a host machine directory
$ docker run --rm -v install_dir:/home/repobee/install_dir \
    -t repobee:latest \
    cp -r /home/repobee/.repobee/* /home/repobee/install_dir
# then mount the host machine directory to the container's install dir
$ docker run --rm -v install_dir:/home/repobee/.repobee \
    -it repobee:latest \
    repobee plugin install
```
It's a bit awkward, but it seems to work.

### CODE REVIEW

**Comment by dbosk** [comment]
Shouldn't it be possible to install plugins in an image? For instance, I want to do grading in INDA. Then I use something like this
```Dockerfile
from repobee:latest

RUN repobee plugin install --local path/to/plugin
RUN sudo apt-get install -y some-jdk
```
(I used local just to make it non-interactive install.) And then run it with `docker run -v /path/to/dir/with/config:/home/repobee/.config/repobee/ inda`? Where my config has the credentials for GitHub.

**Comment by dbosk** [comment]
Essentially, the setup I have in mind is to have just my GitHub tokens in the config. The rest will be provided on the command line.

I'll have a Docker image for every assignment that needs grading, with grading and possibly reporting scripts in there. (It might actually be a nested Docker-in-Docker setup for security reasons: grading in the inner, reporting in the outer.)

I want to package both in Docker images so that I can easily deploy grading to any server, Raspberry Pi in my office, a KTH server, at home, wherever. (See [this](https://github.com/dbosk/grader/issues/1).)

**Comment by slarse** [comment]
> Shouldn't it be possible to install plugins in an image? For instance, I want to do grading in INDA. Then I use something like this
> 
> ```dockerfile
> from repobee:latest
> 
> RUN repobee plugin install --local path/to/plugin
> RUN apt-get install -y some-jdk
> ```
> 
> (I used local just to make it non-interactive install.) And then run it with `docker run -v /path/to/dir/with/config:/home/repobee/.config/repobee/ inda`? Where my config has the credentials for GitHub.

Right, that should totally work. I don't use Docker too much :D. I'll give it a try after work today.

Also highlights the need for non-interactive install of a plugin. That's pretty trivial to add so I can have that in the next release.

> Essentially, the setup I have in mind is to have just my GitHub tokens in the config. The rest will be provided on the command line.
> 
> I'll have a Docker image for every assignment (or course would work too) that needs grading, with grading and possibly reporting scripts in there. (It might actually be a nested Docker-in-Docker setup for security reasons: grading in the inner, reporting in the outer.)
> 
> I want to package both in Docker images so that I can easily deploy grading to any server, Raspberry Pi in my office, a KTH server, at home, wherever. (See [this](https://github.com/dbosk/grader/issues/1).)

Yup, I get it. Thanks for the detailed use case!

**Comment by slarse** [comment]
@dbosk I tried it all out and you were right, installing plugins directly in the image works out just fine. The image built from the Dockerfile I've got here seems like a very decent base image, and so I'll merge this now.

I've reserved the repobee namespace on DockerHub as well, I'll figure out the details on how to deploy there later. I'll let you know in the issue once there's actually a public image up!

**Comment by dbosk** [comment]
On tor 26 nov 2020 09:39:48, Simon Larsén wrote:
> @dbosk I tried it all out and you were right, installing plugins 
> directly in the image works out just fine. The image built from the 
> Dockerfile I've got here seems like a very decent base image, and so 
> I'll merge this now.

Excellent!

> 
> I've reserved the repobee namespace on DockerHub as well, I'll figure 
> out the details on how to deploy there later. I'll let you know in the 
> issue once there's actually a public image up!

Pushing it to DockerHub is as easy as Git, it's something along the 
lines of this:
```
docker build -t repobee
docker tag repobee repobee/repobee
docker push repobee/repobee
```
If repobee is also the name of the namespace/user.

**Comment by slarse** [comment]
> Pushing it to DockerHub is as easy as Git, it's something along the lines of this: ``` docker build -t repobee docker tag repobee repobee/repobee docker push repobee/repobee ``` If repobee is also the name of the namespace/user.

Actually, it was even easier than that. I just linked the RepoBee GitHub organization and turned on builds. And now it just does its thing.

You'll find the image at `repobee/repobee:latest`, which builds on each push to master. When I make the next RepoBee release, it will be available as `repobee/repobee:vX.Y.Z`

**Comment by dbosk** [comment]
That's great! That's how things should work :-)

**Pull request merged**
